### ISSUE TITLE
How do you genrate XML file for the GT ?

### ISSUE THREAD

**Issue by mouradkenk** [beaupreda/clear_mot_metrics#2]
@beaupreda 
could you please tell me the annotation tool that is used to generate XML Ground Truth from a custom video dataset for object tracking.

**Comment by beaupreda** [comment]
Hi,

I used this annotation tool (https://www.jpjodoin.com/urbantracker/tools.html). Also, I heard good things about Viper-GT (http://viper-toolkit.sourceforge.net/docs/quickstart/)

Good luck!

**Comment by mouradkenk** [comment]
thank you so much for your help
Happy New Year
